/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as CustomerRouteImport } from './routes/_customer'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CustomerIndexRouteImport } from './routes/_customer/index'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminStoreSettingsRouteImport } from './routes/admin/store-settings'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPurchaseOrdersRouteImport } from './routes/admin/purchase-orders'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminPosRouteImport } from './routes/admin/pos'
import { Route as AdminOrderQueueRouteImport } from './routes/admin/order-queue'
import { Route as AdminMenuRouteImport } from './routes/admin/menu'
import { Route as AdminActivityLogsRouteImport } from './routes/admin/activity-logs'
import { Route as CustomerProtectedRouteImport } from './routes/_customer/_protected'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminRegisterShiftsIndexRouteImport } from './routes/admin/register-shifts/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin/inventory/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as CustomerProductsIndexRouteImport } from './routes/_customer/products/index'
import { Route as AdminUsersCreateRouteImport } from './routes/admin/users/create'
import { Route as AdminRegisterShiftsHistoryRouteImport } from './routes/admin/register-shifts/history'
import { Route as AdminProductsSettingsRouteImport } from './routes/admin/products/settings'
import { Route as AdminProductsRecipesRouteImport } from './routes/admin/products/recipes'
import { Route as AdminProductsModifiersRouteImport } from './routes/admin/products/modifiers'
import { Route as AdminProductsCreateRouteImport } from './routes/admin/products/create'
import { Route as AdminOrdersCreateRouteImport } from './routes/admin/orders/create'
import { Route as AdminInventoryWasteLogRouteImport } from './routes/admin/inventory/waste-log'
import { Route as AdminInventoryUnitsRouteImport } from './routes/admin/inventory/units'
import { Route as AdminInventoryStockLevelsRouteImport } from './routes/admin/inventory/stock-levels'
import { Route as AdminInventoryProjectionsRouteImport } from './routes/admin/inventory/projections'
import { Route as AdminInventoryIngredientsRouteImport } from './routes/admin/inventory/ingredients'
import { Route as AdminInventoryDeliveriesRouteImport } from './routes/admin/inventory/deliveries'
import { Route as AdminCustomersCreateRouteImport } from './routes/admin/customers/create'
import { Route as AdminrbacPermissionsRouteImport } from './routes/admin/(rbac)/permissions'
import { Route as AdminrbacModulesRouteImport } from './routes/admin/(rbac)/modules'
import { Route as CustomerProductsIdRouteImport } from './routes/_customer/products/$id'
import { Route as CustomerProtectedProfileRouteImport } from './routes/_customer/_protected/profile'
import { Route as CustomerProtectedCheckoutRouteImport } from './routes/_customer/_protected/checkout'
import { Route as CustomerProtectedCartRouteImport } from './routes/_customer/_protected/cart'
import { Route as AdminUsersSlugIndexRouteImport } from './routes/admin/users/$slug/index'
import { Route as AdminProductsIdIndexRouteImport } from './routes/admin/products/$id/index'
import { Route as AdminOrdersIdIndexRouteImport } from './routes/admin/orders/$id/index'
import { Route as AdminCustomersSlugIndexRouteImport } from './routes/admin/customers/$slug/index'
import { Route as AdminrbacRolesIndexRouteImport } from './routes/admin/(rbac)/roles/index'
import { Route as CustomerProtectedOrdersIndexRouteImport } from './routes/_customer/_protected/orders/index'
import { Route as AdminUsersSlugEditRouteImport } from './routes/admin/users/$slug/edit'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products/$id/edit'
import { Route as AdminOrdersIdEditRouteImport } from './routes/admin/orders/$id/edit'
import { Route as AdminCustomersSlugEditRouteImport } from './routes/admin/customers/$slug/edit'
import { Route as AdminrbacRolesCreateRouteImport } from './routes/admin/(rbac)/roles/create'
import { Route as CustomerProtectedOrdersIdRouteImport } from './routes/_customer/_protected/orders/$id'
import { Route as AdminrbacRolesSlugIndexRouteImport } from './routes/admin/(rbac)/roles/$slug/index'
import { Route as AdminrbacRolesSlugEditRouteImport } from './routes/admin/(rbac)/roles/$slug/edit'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStoreSettingsRoute = AdminStoreSettingsRouteImport.update({
  id: '/store-settings',
  path: '/store-settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPurchaseOrdersRoute = AdminPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPosRoute = AdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrderQueueRoute = AdminOrderQueueRouteImport.update({
  id: '/order-queue',
  path: '/order-queue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CustomerProtectedRoute = CustomerProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => CustomerRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegisterShiftsIndexRoute =
  AdminRegisterShiftsIndexRouteImport.update({
    id: '/register-shifts/',
    path: '/register-shifts/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CustomerProductsIndexRoute = CustomerProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminUsersCreateRoute = AdminUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegisterShiftsHistoryRoute =
  AdminRegisterShiftsHistoryRouteImport.update({
    id: '/register-shifts/history',
    path: '/register-shifts/history',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProductsSettingsRoute = AdminProductsSettingsRouteImport.update({
  id: '/products/settings',
  path: '/products/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRecipesRoute = AdminProductsRecipesRouteImport.update({
  id: '/products/recipes',
  path: '/products/recipes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsModifiersRoute = AdminProductsModifiersRouteImport.update({
  id: '/products/modifiers',
  path: '/products/modifiers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsCreateRoute = AdminProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersCreateRoute = AdminOrdersCreateRouteImport.update({
  id: '/orders/create',
  path: '/orders/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryWasteLogRoute = AdminInventoryWasteLogRouteImport.update({
  id: '/inventory/waste-log',
  path: '/inventory/waste-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryUnitsRoute = AdminInventoryUnitsRouteImport.update({
  id: '/inventory/units',
  path: '/inventory/units',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryStockLevelsRoute =
  AdminInventoryStockLevelsRouteImport.update({
    id: '/inventory/stock-levels',
    path: '/inventory/stock-levels',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminInventoryProjectionsRoute =
  AdminInventoryProjectionsRouteImport.update({
    id: '/inventory/projections',
    path: '/inventory/projections',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminInventoryIngredientsRoute =
  AdminInventoryIngredientsRouteImport.update({
    id: '/inventory/ingredients',
    path: '/inventory/ingredients',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminInventoryDeliveriesRoute =
  AdminInventoryDeliveriesRouteImport.update({
    id: '/inventory/deliveries',
    path: '/inventory/deliveries',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCustomersCreateRoute = AdminCustomersCreateRouteImport.update({
  id: '/customers/create',
  path: '/customers/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminrbacPermissionsRoute = AdminrbacPermissionsRouteImport.update({
  id: '/(rbac)/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminrbacModulesRoute = AdminrbacModulesRouteImport.update({
  id: '/(rbac)/modules',
  path: '/modules',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CustomerProductsIdRoute = CustomerProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProtectedProfileRoute =
  CustomerProtectedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => CustomerProtectedRoute,
  } as any)
const CustomerProtectedCheckoutRoute =
  CustomerProtectedCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => CustomerProtectedRoute,
  } as any)
const CustomerProtectedCartRoute = CustomerProtectedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CustomerProtectedRoute,
} as any)
const AdminUsersSlugIndexRoute = AdminUsersSlugIndexRouteImport.update({
  id: '/users/$slug/',
  path: '/users/$slug/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIdIndexRoute = AdminProductsIdIndexRouteImport.update({
  id: '/products/$id/',
  path: '/products/$id/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIdIndexRoute = AdminOrdersIdIndexRouteImport.update({
  id: '/orders/$id/',
  path: '/orders/$id/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersSlugIndexRoute = AdminCustomersSlugIndexRouteImport.update({
  id: '/customers/$slug/',
  path: '/customers/$slug/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminrbacRolesIndexRoute = AdminrbacRolesIndexRouteImport.update({
  id: '/(rbac)/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CustomerProtectedOrdersIndexRoute =
  CustomerProtectedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => CustomerProtectedRoute,
  } as any)
const AdminUsersSlugEditRoute = AdminUsersSlugEditRouteImport.update({
  id: '/users/$slug/edit',
  path: '/users/$slug/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIdEditRoute = AdminOrdersIdEditRouteImport.update({
  id: '/orders/$id/edit',
  path: '/orders/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersSlugEditRoute = AdminCustomersSlugEditRouteImport.update({
  id: '/customers/$slug/edit',
  path: '/customers/$slug/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminrbacRolesCreateRoute = AdminrbacRolesCreateRouteImport.update({
  id: '/(rbac)/roles/create',
  path: '/roles/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CustomerProtectedOrdersIdRoute =
  CustomerProtectedOrdersIdRouteImport.update({
    id: '/orders/$id',
    path: '/orders/$id',
    getParentRoute: () => CustomerProtectedRoute,
  } as any)
const AdminrbacRolesSlugIndexRoute = AdminrbacRolesSlugIndexRouteImport.update({
  id: '/(rbac)/roles/$slug/',
  path: '/roles/$slug/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminrbacRolesSlugEditRoute = AdminrbacRolesSlugEditRouteImport.update({
  id: '/(rbac)/roles/$slug/edit',
  path: '/roles/$slug/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/': typeof CustomerIndexRoute
  '/not-found': typeof NotFoundRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/order-queue': typeof AdminOrderQueueRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/store-settings': typeof AdminStoreSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/cart': typeof CustomerProtectedCartRoute
  '/checkout': typeof CustomerProtectedCheckoutRoute
  '/profile': typeof CustomerProtectedProfileRoute
  '/products/$id': typeof CustomerProductsIdRoute
  '/admin/modules': typeof AdminrbacModulesRoute
  '/admin/permissions': typeof AdminrbacPermissionsRoute
  '/admin/customers/create': typeof AdminCustomersCreateRoute
  '/admin/inventory/deliveries': typeof AdminInventoryDeliveriesRoute
  '/admin/inventory/ingredients': typeof AdminInventoryIngredientsRoute
  '/admin/inventory/projections': typeof AdminInventoryProjectionsRoute
  '/admin/inventory/stock-levels': typeof AdminInventoryStockLevelsRoute
  '/admin/inventory/units': typeof AdminInventoryUnitsRoute
  '/admin/inventory/waste-log': typeof AdminInventoryWasteLogRoute
  '/admin/orders/create': typeof AdminOrdersCreateRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/products/modifiers': typeof AdminProductsModifiersRoute
  '/admin/products/recipes': typeof AdminProductsRecipesRoute
  '/admin/products/settings': typeof AdminProductsSettingsRoute
  '/admin/register-shifts/history': typeof AdminRegisterShiftsHistoryRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/products/': typeof CustomerProductsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/register-shifts/': typeof AdminRegisterShiftsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/orders/$id': typeof CustomerProtectedOrdersIdRoute
  '/admin/roles/create': typeof AdminrbacRolesCreateRoute
  '/admin/customers/$slug/edit': typeof AdminCustomersSlugEditRoute
  '/admin/orders/$id/edit': typeof AdminOrdersIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/users/$slug/edit': typeof AdminUsersSlugEditRoute
  '/orders/': typeof CustomerProtectedOrdersIndexRoute
  '/admin/roles/': typeof AdminrbacRolesIndexRoute
  '/admin/customers/$slug/': typeof AdminCustomersSlugIndexRoute
  '/admin/orders/$id/': typeof AdminOrdersIdIndexRoute
  '/admin/products/$id/': typeof AdminProductsIdIndexRoute
  '/admin/users/$slug/': typeof AdminUsersSlugIndexRoute
  '/admin/roles/$slug/edit': typeof AdminrbacRolesSlugEditRoute
  '/admin/roles/$slug/': typeof AdminrbacRolesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/not-found': typeof NotFoundRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/': typeof CustomerIndexRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/order-queue': typeof AdminOrderQueueRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/store-settings': typeof AdminStoreSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/cart': typeof CustomerProtectedCartRoute
  '/checkout': typeof CustomerProtectedCheckoutRoute
  '/profile': typeof CustomerProtectedProfileRoute
  '/products/$id': typeof CustomerProductsIdRoute
  '/admin/modules': typeof AdminrbacModulesRoute
  '/admin/permissions': typeof AdminrbacPermissionsRoute
  '/admin/customers/create': typeof AdminCustomersCreateRoute
  '/admin/inventory/deliveries': typeof AdminInventoryDeliveriesRoute
  '/admin/inventory/ingredients': typeof AdminInventoryIngredientsRoute
  '/admin/inventory/projections': typeof AdminInventoryProjectionsRoute
  '/admin/inventory/stock-levels': typeof AdminInventoryStockLevelsRoute
  '/admin/inventory/units': typeof AdminInventoryUnitsRoute
  '/admin/inventory/waste-log': typeof AdminInventoryWasteLogRoute
  '/admin/orders/create': typeof AdminOrdersCreateRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/products/modifiers': typeof AdminProductsModifiersRoute
  '/admin/products/recipes': typeof AdminProductsRecipesRoute
  '/admin/products/settings': typeof AdminProductsSettingsRoute
  '/admin/register-shifts/history': typeof AdminRegisterShiftsHistoryRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/products': typeof CustomerProductsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/register-shifts': typeof AdminRegisterShiftsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/orders/$id': typeof CustomerProtectedOrdersIdRoute
  '/admin/roles/create': typeof AdminrbacRolesCreateRoute
  '/admin/customers/$slug/edit': typeof AdminCustomersSlugEditRoute
  '/admin/orders/$id/edit': typeof AdminOrdersIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/users/$slug/edit': typeof AdminUsersSlugEditRoute
  '/orders': typeof CustomerProtectedOrdersIndexRoute
  '/admin/roles': typeof AdminrbacRolesIndexRoute
  '/admin/customers/$slug': typeof AdminCustomersSlugIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdIndexRoute
  '/admin/products/$id': typeof AdminProductsIdIndexRoute
  '/admin/users/$slug': typeof AdminUsersSlugIndexRoute
  '/admin/roles/$slug/edit': typeof AdminrbacRolesSlugEditRoute
  '/admin/roles/$slug': typeof AdminrbacRolesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_customer': typeof CustomerRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/_customer/_protected': typeof CustomerProtectedRouteWithChildren
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/order-queue': typeof AdminOrderQueueRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/store-settings': typeof AdminStoreSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/_customer/': typeof CustomerIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_customer/_protected/cart': typeof CustomerProtectedCartRoute
  '/_customer/_protected/checkout': typeof CustomerProtectedCheckoutRoute
  '/_customer/_protected/profile': typeof CustomerProtectedProfileRoute
  '/_customer/products/$id': typeof CustomerProductsIdRoute
  '/admin/(rbac)/modules': typeof AdminrbacModulesRoute
  '/admin/(rbac)/permissions': typeof AdminrbacPermissionsRoute
  '/admin/customers/create': typeof AdminCustomersCreateRoute
  '/admin/inventory/deliveries': typeof AdminInventoryDeliveriesRoute
  '/admin/inventory/ingredients': typeof AdminInventoryIngredientsRoute
  '/admin/inventory/projections': typeof AdminInventoryProjectionsRoute
  '/admin/inventory/stock-levels': typeof AdminInventoryStockLevelsRoute
  '/admin/inventory/units': typeof AdminInventoryUnitsRoute
  '/admin/inventory/waste-log': typeof AdminInventoryWasteLogRoute
  '/admin/orders/create': typeof AdminOrdersCreateRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/products/modifiers': typeof AdminProductsModifiersRoute
  '/admin/products/recipes': typeof AdminProductsRecipesRoute
  '/admin/products/settings': typeof AdminProductsSettingsRoute
  '/admin/register-shifts/history': typeof AdminRegisterShiftsHistoryRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/_customer/products/': typeof CustomerProductsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/register-shifts/': typeof AdminRegisterShiftsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_customer/_protected/orders/$id': typeof CustomerProtectedOrdersIdRoute
  '/admin/(rbac)/roles/create': typeof AdminrbacRolesCreateRoute
  '/admin/customers/$slug/edit': typeof AdminCustomersSlugEditRoute
  '/admin/orders/$id/edit': typeof AdminOrdersIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/users/$slug/edit': typeof AdminUsersSlugEditRoute
  '/_customer/_protected/orders/': typeof CustomerProtectedOrdersIndexRoute
  '/admin/(rbac)/roles/': typeof AdminrbacRolesIndexRoute
  '/admin/customers/$slug/': typeof AdminCustomersSlugIndexRoute
  '/admin/orders/$id/': typeof AdminOrdersIdIndexRoute
  '/admin/products/$id/': typeof AdminProductsIdIndexRoute
  '/admin/users/$slug/': typeof AdminUsersSlugIndexRoute
  '/admin/(rbac)/roles/$slug/edit': typeof AdminrbacRolesSlugEditRoute
  '/admin/(rbac)/roles/$slug/': typeof AdminrbacRolesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/not-found'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/activity-logs'
    | '/admin/menu'
    | '/admin/order-queue'
    | '/admin/pos'
    | '/admin/profile'
    | '/admin/purchase-orders'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/store-settings'
    | '/admin/suppliers'
    | '/admin/transactions'
    | '/admin/'
    | '/cart'
    | '/checkout'
    | '/profile'
    | '/products/$id'
    | '/admin/modules'
    | '/admin/permissions'
    | '/admin/customers/create'
    | '/admin/inventory/deliveries'
    | '/admin/inventory/ingredients'
    | '/admin/inventory/projections'
    | '/admin/inventory/stock-levels'
    | '/admin/inventory/units'
    | '/admin/inventory/waste-log'
    | '/admin/orders/create'
    | '/admin/products/create'
    | '/admin/products/modifiers'
    | '/admin/products/recipes'
    | '/admin/products/settings'
    | '/admin/register-shifts/history'
    | '/admin/users/create'
    | '/products/'
    | '/admin/customers/'
    | '/admin/inventory/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/register-shifts/'
    | '/admin/users/'
    | '/orders/$id'
    | '/admin/roles/create'
    | '/admin/customers/$slug/edit'
    | '/admin/orders/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/users/$slug/edit'
    | '/orders/'
    | '/admin/roles/'
    | '/admin/customers/$slug/'
    | '/admin/orders/$id/'
    | '/admin/products/$id/'
    | '/admin/users/$slug/'
    | '/admin/roles/$slug/edit'
    | '/admin/roles/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/not-found'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/'
    | '/admin/activity-logs'
    | '/admin/menu'
    | '/admin/order-queue'
    | '/admin/pos'
    | '/admin/profile'
    | '/admin/purchase-orders'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/store-settings'
    | '/admin/suppliers'
    | '/admin/transactions'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/profile'
    | '/products/$id'
    | '/admin/modules'
    | '/admin/permissions'
    | '/admin/customers/create'
    | '/admin/inventory/deliveries'
    | '/admin/inventory/ingredients'
    | '/admin/inventory/projections'
    | '/admin/inventory/stock-levels'
    | '/admin/inventory/units'
    | '/admin/inventory/waste-log'
    | '/admin/orders/create'
    | '/admin/products/create'
    | '/admin/products/modifiers'
    | '/admin/products/recipes'
    | '/admin/products/settings'
    | '/admin/register-shifts/history'
    | '/admin/users/create'
    | '/products'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/register-shifts'
    | '/admin/users'
    | '/orders/$id'
    | '/admin/roles/create'
    | '/admin/customers/$slug/edit'
    | '/admin/orders/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/users/$slug/edit'
    | '/orders'
    | '/admin/roles'
    | '/admin/customers/$slug'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/users/$slug'
    | '/admin/roles/$slug/edit'
    | '/admin/roles/$slug'
  id:
    | '__root__'
    | '/(auth)'
    | '/admin'
    | '/_customer'
    | '/not-found'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/_customer/_protected'
    | '/admin/activity-logs'
    | '/admin/menu'
    | '/admin/order-queue'
    | '/admin/pos'
    | '/admin/profile'
    | '/admin/purchase-orders'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/store-settings'
    | '/admin/suppliers'
    | '/admin/transactions'
    | '/_customer/'
    | '/admin/'
    | '/_customer/_protected/cart'
    | '/_customer/_protected/checkout'
    | '/_customer/_protected/profile'
    | '/_customer/products/$id'
    | '/admin/(rbac)/modules'
    | '/admin/(rbac)/permissions'
    | '/admin/customers/create'
    | '/admin/inventory/deliveries'
    | '/admin/inventory/ingredients'
    | '/admin/inventory/projections'
    | '/admin/inventory/stock-levels'
    | '/admin/inventory/units'
    | '/admin/inventory/waste-log'
    | '/admin/orders/create'
    | '/admin/products/create'
    | '/admin/products/modifiers'
    | '/admin/products/recipes'
    | '/admin/products/settings'
    | '/admin/register-shifts/history'
    | '/admin/users/create'
    | '/_customer/products/'
    | '/admin/customers/'
    | '/admin/inventory/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/register-shifts/'
    | '/admin/users/'
    | '/_customer/_protected/orders/$id'
    | '/admin/(rbac)/roles/create'
    | '/admin/customers/$slug/edit'
    | '/admin/orders/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/users/$slug/edit'
    | '/_customer/_protected/orders/'
    | '/admin/(rbac)/roles/'
    | '/admin/customers/$slug/'
    | '/admin/orders/$id/'
    | '/admin/products/$id/'
    | '/admin/users/$slug/'
    | '/admin/(rbac)/roles/$slug/edit'
    | '/admin/(rbac)/roles/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_customer/': {
      id: '/_customer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/store-settings': {
      id: '/admin/store-settings'
      path: '/store-settings'
      fullPath: '/admin/store-settings'
      preLoaderRoute: typeof AdminStoreSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/purchase-orders': {
      id: '/admin/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/admin/purchase-orders'
      preLoaderRoute: typeof AdminPurchaseOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pos': {
      id: '/admin/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AdminPosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/order-queue': {
      id: '/admin/order-queue'
      path: '/order-queue'
      fullPath: '/admin/order-queue'
      preLoaderRoute: typeof AdminOrderQueueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_customer/_protected': {
      id: '/_customer/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerProtectedRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/register-shifts/': {
      id: '/admin/register-shifts/'
      path: '/register-shifts'
      fullPath: '/admin/register-shifts/'
      preLoaderRoute: typeof AdminRegisterShiftsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_customer/products/': {
      id: '/_customer/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof CustomerProductsIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/users/create': {
      id: '/admin/users/create'
      path: '/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AdminUsersCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/register-shifts/history': {
      id: '/admin/register-shifts/history'
      path: '/register-shifts/history'
      fullPath: '/admin/register-shifts/history'
      preLoaderRoute: typeof AdminRegisterShiftsHistoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/settings': {
      id: '/admin/products/settings'
      path: '/products/settings'
      fullPath: '/admin/products/settings'
      preLoaderRoute: typeof AdminProductsSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/recipes': {
      id: '/admin/products/recipes'
      path: '/products/recipes'
      fullPath: '/admin/products/recipes'
      preLoaderRoute: typeof AdminProductsRecipesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/modifiers': {
      id: '/admin/products/modifiers'
      path: '/products/modifiers'
      fullPath: '/admin/products/modifiers'
      preLoaderRoute: typeof AdminProductsModifiersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/create': {
      id: '/admin/products/create'
      path: '/products/create'
      fullPath: '/admin/products/create'
      preLoaderRoute: typeof AdminProductsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/create': {
      id: '/admin/orders/create'
      path: '/orders/create'
      fullPath: '/admin/orders/create'
      preLoaderRoute: typeof AdminOrdersCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory/waste-log': {
      id: '/admin/inventory/waste-log'
      path: '/inventory/waste-log'
      fullPath: '/admin/inventory/waste-log'
      preLoaderRoute: typeof AdminInventoryWasteLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory/units': {
      id: '/admin/inventory/units'
      path: '/inventory/units'
      fullPath: '/admin/inventory/units'
      preLoaderRoute: typeof AdminInventoryUnitsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory/stock-levels': {
      id: '/admin/inventory/stock-levels'
      path: '/inventory/stock-levels'
      fullPath: '/admin/inventory/stock-levels'
      preLoaderRoute: typeof AdminInventoryStockLevelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory/projections': {
      id: '/admin/inventory/projections'
      path: '/inventory/projections'
      fullPath: '/admin/inventory/projections'
      preLoaderRoute: typeof AdminInventoryProjectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory/ingredients': {
      id: '/admin/inventory/ingredients'
      path: '/inventory/ingredients'
      fullPath: '/admin/inventory/ingredients'
      preLoaderRoute: typeof AdminInventoryIngredientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory/deliveries': {
      id: '/admin/inventory/deliveries'
      path: '/inventory/deliveries'
      fullPath: '/admin/inventory/deliveries'
      preLoaderRoute: typeof AdminInventoryDeliveriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/create': {
      id: '/admin/customers/create'
      path: '/customers/create'
      fullPath: '/admin/customers/create'
      preLoaderRoute: typeof AdminCustomersCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/(rbac)/permissions': {
      id: '/admin/(rbac)/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminrbacPermissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/(rbac)/modules': {
      id: '/admin/(rbac)/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminrbacModulesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_customer/products/$id': {
      id: '/_customer/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof CustomerProductsIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/_protected/profile': {
      id: '/_customer/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof CustomerProtectedProfileRouteImport
      parentRoute: typeof CustomerProtectedRoute
    }
    '/_customer/_protected/checkout': {
      id: '/_customer/_protected/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CustomerProtectedCheckoutRouteImport
      parentRoute: typeof CustomerProtectedRoute
    }
    '/_customer/_protected/cart': {
      id: '/_customer/_protected/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CustomerProtectedCartRouteImport
      parentRoute: typeof CustomerProtectedRoute
    }
    '/admin/users/$slug/': {
      id: '/admin/users/$slug/'
      path: '/users/$slug'
      fullPath: '/admin/users/$slug/'
      preLoaderRoute: typeof AdminUsersSlugIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/$id/': {
      id: '/admin/products/$id/'
      path: '/products/$id'
      fullPath: '/admin/products/$id/'
      preLoaderRoute: typeof AdminProductsIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/$id/': {
      id: '/admin/orders/$id/'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id/'
      preLoaderRoute: typeof AdminOrdersIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/$slug/': {
      id: '/admin/customers/$slug/'
      path: '/customers/$slug'
      fullPath: '/admin/customers/$slug/'
      preLoaderRoute: typeof AdminCustomersSlugIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/(rbac)/roles/': {
      id: '/admin/(rbac)/roles/'
      path: '/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AdminrbacRolesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_customer/_protected/orders/': {
      id: '/_customer/_protected/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof CustomerProtectedOrdersIndexRouteImport
      parentRoute: typeof CustomerProtectedRoute
    }
    '/admin/users/$slug/edit': {
      id: '/admin/users/$slug/edit'
      path: '/users/$slug/edit'
      fullPath: '/admin/users/$slug/edit'
      preLoaderRoute: typeof AdminUsersSlugEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/$id/edit': {
      id: '/admin/orders/$id/edit'
      path: '/orders/$id/edit'
      fullPath: '/admin/orders/$id/edit'
      preLoaderRoute: typeof AdminOrdersIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/$slug/edit': {
      id: '/admin/customers/$slug/edit'
      path: '/customers/$slug/edit'
      fullPath: '/admin/customers/$slug/edit'
      preLoaderRoute: typeof AdminCustomersSlugEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/(rbac)/roles/create': {
      id: '/admin/(rbac)/roles/create'
      path: '/roles/create'
      fullPath: '/admin/roles/create'
      preLoaderRoute: typeof AdminrbacRolesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_customer/_protected/orders/$id': {
      id: '/_customer/_protected/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof CustomerProtectedOrdersIdRouteImport
      parentRoute: typeof CustomerProtectedRoute
    }
    '/admin/(rbac)/roles/$slug/': {
      id: '/admin/(rbac)/roles/$slug/'
      path: '/roles/$slug'
      fullPath: '/admin/roles/$slug/'
      preLoaderRoute: typeof AdminrbacRolesSlugIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/(rbac)/roles/$slug/edit': {
      id: '/admin/(rbac)/roles/$slug/edit'
      path: '/roles/$slug/edit'
      fullPath: '/admin/roles/$slug/edit'
      preLoaderRoute: typeof AdminrbacRolesSlugEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrderQueueRoute: typeof AdminOrderQueueRoute
  AdminPosRoute: typeof AdminPosRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminPurchaseOrdersRoute: typeof AdminPurchaseOrdersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminStoreSettingsRoute: typeof AdminStoreSettingsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminrbacModulesRoute: typeof AdminrbacModulesRoute
  AdminrbacPermissionsRoute: typeof AdminrbacPermissionsRoute
  AdminCustomersCreateRoute: typeof AdminCustomersCreateRoute
  AdminInventoryDeliveriesRoute: typeof AdminInventoryDeliveriesRoute
  AdminInventoryIngredientsRoute: typeof AdminInventoryIngredientsRoute
  AdminInventoryProjectionsRoute: typeof AdminInventoryProjectionsRoute
  AdminInventoryStockLevelsRoute: typeof AdminInventoryStockLevelsRoute
  AdminInventoryUnitsRoute: typeof AdminInventoryUnitsRoute
  AdminInventoryWasteLogRoute: typeof AdminInventoryWasteLogRoute
  AdminOrdersCreateRoute: typeof AdminOrdersCreateRoute
  AdminProductsCreateRoute: typeof AdminProductsCreateRoute
  AdminProductsModifiersRoute: typeof AdminProductsModifiersRoute
  AdminProductsRecipesRoute: typeof AdminProductsRecipesRoute
  AdminProductsSettingsRoute: typeof AdminProductsSettingsRoute
  AdminRegisterShiftsHistoryRoute: typeof AdminRegisterShiftsHistoryRoute
  AdminUsersCreateRoute: typeof AdminUsersCreateRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminRegisterShiftsIndexRoute: typeof AdminRegisterShiftsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminrbacRolesCreateRoute: typeof AdminrbacRolesCreateRoute
  AdminCustomersSlugEditRoute: typeof AdminCustomersSlugEditRoute
  AdminOrdersIdEditRoute: typeof AdminOrdersIdEditRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
  AdminUsersSlugEditRoute: typeof AdminUsersSlugEditRoute
  AdminrbacRolesIndexRoute: typeof AdminrbacRolesIndexRoute
  AdminCustomersSlugIndexRoute: typeof AdminCustomersSlugIndexRoute
  AdminOrdersIdIndexRoute: typeof AdminOrdersIdIndexRoute
  AdminProductsIdIndexRoute: typeof AdminProductsIdIndexRoute
  AdminUsersSlugIndexRoute: typeof AdminUsersSlugIndexRoute
  AdminrbacRolesSlugEditRoute: typeof AdminrbacRolesSlugEditRoute
  AdminrbacRolesSlugIndexRoute: typeof AdminrbacRolesSlugIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrderQueueRoute: AdminOrderQueueRoute,
  AdminPosRoute: AdminPosRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminPurchaseOrdersRoute: AdminPurchaseOrdersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminStoreSettingsRoute: AdminStoreSettingsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminrbacModulesRoute: AdminrbacModulesRoute,
  AdminrbacPermissionsRoute: AdminrbacPermissionsRoute,
  AdminCustomersCreateRoute: AdminCustomersCreateRoute,
  AdminInventoryDeliveriesRoute: AdminInventoryDeliveriesRoute,
  AdminInventoryIngredientsRoute: AdminInventoryIngredientsRoute,
  AdminInventoryProjectionsRoute: AdminInventoryProjectionsRoute,
  AdminInventoryStockLevelsRoute: AdminInventoryStockLevelsRoute,
  AdminInventoryUnitsRoute: AdminInventoryUnitsRoute,
  AdminInventoryWasteLogRoute: AdminInventoryWasteLogRoute,
  AdminOrdersCreateRoute: AdminOrdersCreateRoute,
  AdminProductsCreateRoute: AdminProductsCreateRoute,
  AdminProductsModifiersRoute: AdminProductsModifiersRoute,
  AdminProductsRecipesRoute: AdminProductsRecipesRoute,
  AdminProductsSettingsRoute: AdminProductsSettingsRoute,
  AdminRegisterShiftsHistoryRoute: AdminRegisterShiftsHistoryRoute,
  AdminUsersCreateRoute: AdminUsersCreateRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminRegisterShiftsIndexRoute: AdminRegisterShiftsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminrbacRolesCreateRoute: AdminrbacRolesCreateRoute,
  AdminCustomersSlugEditRoute: AdminCustomersSlugEditRoute,
  AdminOrdersIdEditRoute: AdminOrdersIdEditRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
  AdminUsersSlugEditRoute: AdminUsersSlugEditRoute,
  AdminrbacRolesIndexRoute: AdminrbacRolesIndexRoute,
  AdminCustomersSlugIndexRoute: AdminCustomersSlugIndexRoute,
  AdminOrdersIdIndexRoute: AdminOrdersIdIndexRoute,
  AdminProductsIdIndexRoute: AdminProductsIdIndexRoute,
  AdminUsersSlugIndexRoute: AdminUsersSlugIndexRoute,
  AdminrbacRolesSlugEditRoute: AdminrbacRolesSlugEditRoute,
  AdminrbacRolesSlugIndexRoute: AdminrbacRolesSlugIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CustomerProtectedRouteChildren {
  CustomerProtectedCartRoute: typeof CustomerProtectedCartRoute
  CustomerProtectedCheckoutRoute: typeof CustomerProtectedCheckoutRoute
  CustomerProtectedProfileRoute: typeof CustomerProtectedProfileRoute
  CustomerProtectedOrdersIdRoute: typeof CustomerProtectedOrdersIdRoute
  CustomerProtectedOrdersIndexRoute: typeof CustomerProtectedOrdersIndexRoute
}

const CustomerProtectedRouteChildren: CustomerProtectedRouteChildren = {
  CustomerProtectedCartRoute: CustomerProtectedCartRoute,
  CustomerProtectedCheckoutRoute: CustomerProtectedCheckoutRoute,
  CustomerProtectedProfileRoute: CustomerProtectedProfileRoute,
  CustomerProtectedOrdersIdRoute: CustomerProtectedOrdersIdRoute,
  CustomerProtectedOrdersIndexRoute: CustomerProtectedOrdersIndexRoute,
}

const CustomerProtectedRouteWithChildren =
  CustomerProtectedRoute._addFileChildren(CustomerProtectedRouteChildren)

interface CustomerRouteChildren {
  CustomerProtectedRoute: typeof CustomerProtectedRouteWithChildren
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerProductsIdRoute: typeof CustomerProductsIdRoute
  CustomerProductsIndexRoute: typeof CustomerProductsIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerProtectedRoute: CustomerProtectedRouteWithChildren,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerProductsIdRoute: CustomerProductsIdRoute,
  CustomerProductsIndexRoute: CustomerProductsIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
